var tr = document.createElement('tr');
var td1 = document.createElement('td');
var td2 = document.createElement('td');
var a = document.createElement('a');
var table = document.getElementsByTagName("table")[0];
var apis = [
	"javascript:(function(){var api='https://wn.run/f/#';open(api+location.href);})()",
	"javascript:(function(){var api='https://cli.im/api/qrcode/code?text=';open(api+location.href);})()",
	"javascript:(function(){var api='http://sqv6.com/api/api/bdtq.php?msg=';for(;;){var text=prompt('请输入城市名：','');if(text==null){break;}else if(text!=''){open(api+text);break;}else{alert('请输入城市名！！！');}}})()",
	"javascript:(function(){var api='https://img.chkaja.com/weibo_url.php?url=';open(api+location.href);})()",
	"javascript:(function(){var api='http://qqop.ziyia.cn/wzsuoduan/api.php?url=';open(api+location.href);})()",
	"javascript:(function(){var api='https://wanneng.run/short_url/url.php?url=';open(api+location.href);})()",
	"javascript:(function(){var api='http://suo.la/api.asp?url=';open(api+location.href);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?encode=text';open(api);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?c=a&encode=text';open(api);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?c=b&encode=text';open(api);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?c=c&encode=text';open(api);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?c=d&encode=text';open(api);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?c=e&encode=text';open(api);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?c=f&encode=text';open(api);})()",
	"javascript:(function(){var api='https://v1.hitokoto.cn/?c=g&encode=text';open(api);})()",
	"javascript:(function(){var api='https://api.qinor.cn/soup';open(api);})()",
	"javascript:(function(){var api='https://teshenqi.com/api/jitang.php';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/yan/api.php';open(api);})()",
	"javascript:(function(){var api='https://api.ooopn.com/ciba/api.php?type=text';open(api);})()",
	"javascript:(function(){var api='https://api.uixsj.cn/bing/bing.php';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjtx/api.php?lx=a1&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjtx/api.php?lx=b1&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjtx/api.php?lx=c1&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjtx/api.php?lx=c3&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjtx/api.php?lx=c2&format=images';open(api);})()",
	"javascript:(function(){var api='https://api.mlwei.com/img/api/';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?format=images';open(api);})()",
	"javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?lx=dongman';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?lx=dongman&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?lx=meizi';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?lx=meizi&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?lx=fengjing';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?lx=fengjing&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?lx=suiji';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?lx=suiji&format=images';open(api);})()",
	"javascript:(function(){var api='https://www.juanhaoduo.com/tools/tu/tu.php';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?method=mobile&format=images';open(api);})()",
	"javascript:(function(){var api='http://qqop.ziyia.cn/random/api.php?n=1&shuc=tp';open(api);})()",
	"javascript:(function(){var api='http://qqop.ziyia.cn/random/api.php?n=2&shuc=tp';open(api);})()",
	"javascript:(function(){var api='http://qqop.ziyia.cn/random/api.php?n=3&shuc=tp';open(api);})()",
	"javascript:(function(){var api='http://qqop.ziyia.cn/random/api.php?n=4&shuc=tp';open(api);})()",
	"javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?method=mobile&lx=dongman';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?method=mobile&lx=dongman&format=images';open(api);})()",
	"javascript:(function(){var api='http://qqop.ziyia.cn/random/api.php?n=5&shuc=tp';open(api);})()",
	"javascript:(function(){var api='http://qqop.ziyia.cn/random/api.php?n=6&shuc=tp';open(api);})()",
	// "javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?method=mobile&lx=meizi';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?method=mobile&lx=meizi&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?method=mobile&lx=fengjing';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?method=mobile&lx=fengjing&format=images';open(api);})()",
	"javascript:(function(){var api='http://api.diyigzs.com/sjbz/api.php?method=mobile&lx=suiji';open(api);})()",
	"javascript:(function(){var api='http://api.btstu.cn/sjbz/api.php?method=mobile&lx=suiji&format=images';open(api);})()",
];
var names = [
	"万能命令<br/><span>任意网站的快捷命令</span>",
	"二维码生成<br/><span>网址变成二维码</span>",
	"天气查询<br/><span>输入城市名查询天气状况</span>",
	"t.cn - 短链接<br/><span>长网址变成短网址</span>",
	"url.cn - 短链接<br/><span>长网址变成短网址</span>",
	"suo.im - 短链接<br/><span>长网址变成短网址</span>",
	"suo.la - 短链接<br/><span>长网址变成短网址</span>",
	"一言 - 任意<br/><span>随机一句话</span>",
	"一言 - 动漫<br/><span>随机一句话</span>",
	"一言 - 漫画<br/><span>随机一句话</span>",
	"一言 - 游戏<br/><span>随机一句话</span>",
	"一言 - 小说<br/><span>随机一句话</span>",
	"一言 - 原创<br/><span>随机一句话</span>",
	"一言 - 网络<br/><span>随机一句话</span>",
	"一言 - 其他<br/><span>随机一句话</span>",
	"毒鸡汤<br/><span>壮士可要来一碗！</span>",
	"心灵鸡汤<br/><span>来碗鸡汤吧！</span>",
	"随机语录<br/><span>随机一句语录</span>",
	"每日一句<br/><span>每天一句话</span>",
	"每日必应<br/><span>必应背景图</span>",
	"随机头像 - 男头<br/><span>随机头像</span>",
	"随机头像 - 女头<br/><span>随机头像</span>",
	"随机头像 - 动漫<br/><span>随机头像</span>",
	"随机头像 - 动漫男头<br/><span>随机头像</span>",
	"随机头像 - 动漫女头<br/><span>随机头像</span>",
	"随机横屏图 - 任意1<br/><span>随机横屏图</span>",
	"随机横屏图 - 任意2<br/><span>随机横屏图</span>",
	"随机横屏图 - 动漫1<br/><span>随机横屏图</span>",
	"随机横屏图 - 动漫2<br/><span>随机横屏图</span>",
	"随机横屏图 - 美女1<br/><span>随机横屏图</span>",
	"随机横屏图 - 美女2<br/><span>随机横屏图</span>",
	"随机横屏图 - 风景1<br/><span>随机横屏图</span>",
	"随机横屏图 - 风景2<br/><span>随机横屏图</span>",
	"随机横屏图 - 动漫/美女1<br/><span>随机横屏图</span>",
	"随机横屏图 - 动漫/美女2<br/><span>随机横屏图</span>",
	"随机竖屏图 - 任意1<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 任意2<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 少女<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 二次元动漫<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 小姐姐<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 动漫1<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 动漫2<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 动漫3<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 日系美女<br/><span>随机竖屏图</span>",
	// "随机竖屏图 - 最新采集<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 美女1<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 美女2<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 风景1<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 风景2<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 动漫/美女1<br/><span>随机竖屏图</span>",
	"随机竖屏图 - 动漫/美女2<br/><span>随机竖屏图</span>",
];
for (var i = 0; i < apis.length; i++, tr = document.createElement('tr'), td1 = document.createElement('td'), td2 =
	document.createElement('td'), a = document.createElement('a')) {
	td1.innerHTML = names[i];
	a.onclick = function() {
		alert('请把按钮拖动到书签栏!');
	};
	a.href = apis[i];
	a.innerHTML = names[i].split("<br/>")[0];
	td2.appendChild(a);
	tr.appendChild(td1);
	tr.appendChild(td2);
	table.appendChild(tr);
};
